import Home from '@/components/Home/Home'
import Head from 'next/head'
import { dummyPosts } from '../../Dummy-data'

export default function BlogNextJS() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Home  posts={dummyPosts} status="idle" errorMessage="" />
      </div>
    </>
  )
}
