import { observer } from "mobx-react-lite";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";

import Home from "@/components/Home/Home";
import { IServerRenderProps } from "@/shared/types";
import { HomeData, HomeStore } from "@/stores/HomeStore";

export type IHomeProps =
  | ({
    pageData: HomeData;
  } & IServerRenderProps);

export const baseUrl = "https://newsapi.org/v2/everything?q=tesla&from=2023-05-28&sortBy=publishedAt&apiKey=1b4b963ff661428ebe4b361015bd015c";

const IndexPage: NextPage<IHomeProps> = observer<IHomeProps>((props) => {
  const { posts } = props.pageData;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Home posts={posts} status="idle" errorMessage="" />
      </div>
    </>
  );
});

export async function getServerSideProps(ctx: any) {
  const pageStore = new HomeStore();
  await pageStore.fetchPageDataServer();

  return {
    props: {
      pageData: pageStore.dehydrate(),
      isServerRender: true,
    },
  };
}
export default IndexPage;
